### ISSUE TITLE
The FoldingTabBar is not displayed when using performSegue

### ISSUE THREAD

**Issue by resand** [Yalantis/FoldingTabBar.iOS#73] opened 2017-01-26 19:46 UTC
When I perform a **performSegue** with code, for example in a **login** when redirecting to the login screen the tabs are not shown, only a black bar comes out; what is this about?
![simulator screen shot 26 01 2017 1 42 49 p m](https://cloud.githubusercontent.com/assets/5307015/22347427/901a7a3c-e3cd-11e6-99e4-f7618986c755.png)

**Comment by knikaha** [comment] 2017-01-31 17:31
yes you should use delegate

**Comment by lukeswitz** [comment] 2017-01-31 17:53
```
 -(void)prepareForSegue:(UIStoryboardSegue *)segue sender:(id)sender {
    if ([segue.identifier isEqualToString:@"yourSegueNameHere"]) {
       
        // Get destination view
        LoginViewControllerName *vc2 = segue.destinationViewController;
    }

```

**Comment by resand** [comment] 2017-01-31 19:35
I did not quite understand the example, they could help me with full functionality please, I'm using Swift 3.

**Comment by lukeswitz** [comment] 2017-01-31 20:38
You need a navigation controller in there to handle what you're trying to do. Here is some reference on view controller handling in Swift http://www.codingexplorer.com/segue-swift-view-controllers/ 

Hope that helps

**Comment by resand** [comment] 2017-02-01 00:47
The function I try to do is a login to a start view, if I enter the Home works correctly; But when I pass from login to homeView is that the bar is left in black....
:S

**Comment by Vodolazkyi** [comment] 2017-04-17 16:14
duplicate of https://github.com/Yalantis/FoldingTabBar.iOS/issues/76

**Closed as completed by Vodolazkyi** 2017-04-17 16:14 UTC
